---
title: "Insights"
author: "Jessica Tan"
date: "7/25/2021"
output: distill::distill_article
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Data

***Q1&2:*** The news dataset comprised 12,928 news articles from 29 newsgroups which were published over 11+ years from Oct 1982 to Mar 2014.  Of the newsgroups, the biggest contributor was News Online Today with 105 articles, and the smallest contributor was World Source with less than 30 articles over the same period. When the 1st news articles on the Gastech contamination issues emerged in 1982, the coverage was made by only 5 newsgroups then, and there was also a 6-year gap from 1985 to 1992 during which there was no reporting on the topic of GASTech's water contamination. 


***Qn3:*** The data retrieved and analysed comprised (i) email headers and (ii) employee records provided for the present 2021 MC1. In addition, the author also retrieved the profiled individuals’ background record file provided for MC1 in the 2014 VastChallenge to support in addressing the requirements of Qn3. Please see Qn3 Reply below for details. 


# Qn1 Reply

To characterize the news data, the sentiment scores of the news articles by each newsgroup was calculated using the AFINN sentiment dictionary. It is noted the Abila Post and the Central Bulletin both had the most negative sentiment score of -1.5 out of the 29 newsgroups whilst The Tulip and The Guide were at the other spectrum with the least negative sentiment score of around -0.7. Overall, the average sentiment scores across the newsgroups were all in the deficit, perhaps reflecting the negative views of the media on the developments in Kronos at large.

Visualisation of the news articles showed similarity in their TFIDF profiles for some news groups. This was followed up by computing the correlation values of news articles across the newsgroups. It was observed that there was high correlation of more than 0.7 in 5 clusters of newsgroups. These clusters were centred around 5 core newsgroups which we can infer as the primary news sources since they acted like a hub linking up all the other newsgroups within their clusters. The 5 primary news sources are (1) “The Abila”, (2) “The World”, (3) “International Times”, (4) “Kronos Star”, and (5) “Homeland Illumination”, and  the other newsgroups surrounding these hubs are the derivative news sources.

Data wrangling was further performed to obtain a data table containing the correlated news article pairs with column details on text-id, published date, title and respective newsgroup for each of the paired news articles. With the this interactive datatable, we would be able to identify the primary and derivative news sources for each highly correlated news article pairs (>0.8 correlation) by comparing their published dates. The article with the earlier date would be the primary source as the later article would essentially be obtaining its text from the primary article after the primary article has been published.

# Qn2 Reply:

The word cloud performed on the consolidated news articles showed the topics surrounding the issue of GASTech’s contamination of water resources in Elodis. Negative key words such as “violent”, “death”, and “protesters” surrounded the discussion of the topic with core parties such as “POK”  and GASTech and its CEO, Sten Sanjorge showing up with high frequency. 
Using the AFINN sentiment dictionary, the word stems of the text in the news articles are calculated for their sentiment scores and the results are reported in an interactive data table to allow user to input word for retrieval of the corresponding sentiment score. These sentiment scores are further applied to word bigrams in news reporting of specific people, places and events. 

In ***reporting of central figures*** in the GASTech contamination saga, it was noted the positive sentiment words such as “like” and “survived” which were bigrams for POK leaders Bodrogi and Carmine weighed significantly to result in positive sentiment scores for these individuals. At the other spectrum were Kronos President Kapelou, Minister Nespola and GASTech CEO Sanjorge with negative sentiment scores due to bigrams such as “threatening”, “no” and “escapes” in the news reporting of these persons.

In ***reporting of key places***, the news sentiment scores vary in tandem with the reporting of events occurring in these places. For example, the numerous protests convening in Elodis resulted in negatively skewed sentiment scores on the associated word bigrams whilst the reported “help” provided to the rural areas resulted in positive word bigrams and corresponding sentiment score.

For ***reporting of significant events***, the sentiment scores seem to be correct for most, i.e. negative sentiment associated with arrests, deaths, protests etc. However, for events such as disease and contamination, the associated words such as “responsible” and “increased” (which are classified by AFINN as positive sentiment words) may have incorrectly tilted the sentiment scores in the positive direction.

Finally, the word bigrams surrounding ***reporting of organizations*** central to the topic such as GASTech, POK, Kronos Government and WFA (NGO) were also retrieved and sentiment-scored. WFA was attributed positive sentiment scores due to its supportive actions in the community. The Government and POK were accorded fairly balanced spread of positive and negative sentiment scores arising from their advocations and the events that occurred. Notably, GASTech derived negative sentiment scores due to the news reporting on issues of water contamination which purportedly caused harm to the people in the community.

# Qn 3

First, the email data was processed into nodes representing persons, and edges representing communication links, for the purpose of performing network analysis of the email data tracked by GASTech staff.  Network graphs were performed across the profiles of the GASTech staff. These provided graphical representation of the communication network over emails by (i) staff names, (ii) citizenship country, (iii) military service branch, and (iv) days of the week to visualise the email network mutation over the course of the week.

In analysis of the network graph by staff names, family surnames related to existing POK members could be seen in the nodes identified. The author then proceeded to set up data tables on (i) employee record and (ii) profiled individuals background record. The former (i) is to provide quick access to staff details based on gender, department, job title, citizenship country and military service type of staff profiled in the email network analysis. The latter (ii) is to trace the profiled staff for affiliations to POK or other external organisation if any. [Note: The external POK background record is obtained from the MC1 data provided in the 2014 VastChallenge.]

By inputting “POK” in the search tab of the abovesaid data table (ii) on profiled individuals background record, all GASTech staff with POK affiliation would be immediately retrieved. In total, there are 5 POK members on GASTech’s employment roll. These are (1) Minke.Mies, (2) Isia.Vann, (3) Loreto.Bodrogi, (4) Hennie.Osvaldo. and (5) Inga.Ferro. To extract all other personnel with external profiles, simply click on the upward arrow at the “POK/Others” column and you could see the other profiled staff such as Edward.Vann who share the same Vann surname with a few important members of the POK as well as Ruscella.Mies.Haber, who is aunt of Minke.Mies. Notably, all the staff with POK affiliation are in the Security Department whilst the other profiled staff are in the Administration Department.

From the network graph by citizenship country, it is noted the majority of GASTech’s staff in Kronos were not locals but citizens of Tethys. In addition, based on the network graph by Military Service Branch, the majority of GASTech staff did not serve in the military. However, for staff who did served in the military, the majority were in Arm Forces of Kronos and these staff formed a tightly knitted group with close and frequent email communication based on the network graph. 
